---
- hosts: localhost
  roles:
  - { role: base,            tags: ['base'] }
  - { role: develop,         tags: ['develop'] }
  - { role: desktop,         tags: ['desktop']}
  # - { role: users,           tags: ['users', 'never'] }
  # - { role: printers,        tags: ['printers'] }
  - { role: browsers,        tags: ['browsers'] }
  # - { role: developer-tools, tags: ['dev-tools'] }
  - { role: editors,         tags: ['editors'] }
  # - { role: media,           tags: ['media'] }
  # - { role: gnome,           tags: ['gnome'] }