- name: add public key
  apt_key:
    id: "{{ item.id }}"
    url: "{{ item.url }}"
    state: present
  with_items: "{{ virtualbox_public_keys }}"
  vars:
    - virtualbox_public_keys:
      - id: 54422A4B98AB5139
        url: https://www.virtualbox.org/download/oracle_vbox.asc
      - id: A2F683C52980AECF
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
  become: yes

- name: add virtualbox repository
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian buster contrib"
    state: present
    update_cache: true
  become: yes

- name: install
  apt:
    name: virtualbox-6.1
    state: present
  become: yes
